/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './modules/__root'
import { Route as NonAuthedRouteImport } from './modules/_nonAuthed/route'
import { Route as AuthedRouteImport } from './modules/_authed/route'
import { Route as HomeIndexImport } from './modules/_home/index'
import { Route as NonAuthedRegisterIndexImport } from './modules/_nonAuthed/register/index'
import { Route as NonAuthedLoginIndexImport } from './modules/_nonAuthed/login/index'
import { Route as AuthedProfileIndexImport } from './modules/_authed/profile/index'
import { Route as NonAuthedLoginSsoCallbackImport } from './modules/_nonAuthed/login/sso-callback'
import { Route as AuthedProfileUsernameImport } from './modules/_authed/profile/$username'

// Create/Update Routes

const NonAuthedRouteRoute = NonAuthedRouteImport.update({
  id: '/_nonAuthed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRouteRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NonAuthedRegisterIndexRoute = NonAuthedRegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => NonAuthedRouteRoute,
} as any)

const NonAuthedLoginIndexRoute = NonAuthedLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => NonAuthedRouteRoute,
} as any)

const AuthedProfileIndexRoute = AuthedProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRouteRoute,
} as any)

const NonAuthedLoginSsoCallbackRoute = NonAuthedLoginSsoCallbackImport.update({
  id: '/login/sso-callback',
  path: '/login/sso-callback',
  getParentRoute: () => NonAuthedRouteRoute,
} as any)

const AuthedProfileUsernameRoute = AuthedProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AuthedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_nonAuthed': {
      id: '/_nonAuthed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NonAuthedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed/profile/$username': {
      id: '/_authed/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthedProfileUsernameImport
      parentRoute: typeof AuthedRouteImport
    }
    '/_nonAuthed/login/sso-callback': {
      id: '/_nonAuthed/login/sso-callback'
      path: '/login/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof NonAuthedLoginSsoCallbackImport
      parentRoute: typeof NonAuthedRouteImport
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileIndexImport
      parentRoute: typeof AuthedRouteImport
    }
    '/_nonAuthed/login/': {
      id: '/_nonAuthed/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NonAuthedLoginIndexImport
      parentRoute: typeof NonAuthedRouteImport
    }
    '/_nonAuthed/register/': {
      id: '/_nonAuthed/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof NonAuthedRegisterIndexImport
      parentRoute: typeof NonAuthedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteRouteChildren {
  AuthedProfileUsernameRoute: typeof AuthedProfileUsernameRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileUsernameRoute: AuthedProfileUsernameRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface NonAuthedRouteRouteChildren {
  NonAuthedLoginSsoCallbackRoute: typeof NonAuthedLoginSsoCallbackRoute
  NonAuthedLoginIndexRoute: typeof NonAuthedLoginIndexRoute
  NonAuthedRegisterIndexRoute: typeof NonAuthedRegisterIndexRoute
}

const NonAuthedRouteRouteChildren: NonAuthedRouteRouteChildren = {
  NonAuthedLoginSsoCallbackRoute: NonAuthedLoginSsoCallbackRoute,
  NonAuthedLoginIndexRoute: NonAuthedLoginIndexRoute,
  NonAuthedRegisterIndexRoute: NonAuthedRegisterIndexRoute,
}

const NonAuthedRouteRouteWithChildren = NonAuthedRouteRoute._addFileChildren(
  NonAuthedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof NonAuthedRouteRouteWithChildren
  '/': typeof HomeIndexRoute
  '/profile/$username': typeof AuthedProfileUsernameRoute
  '/login/sso-callback': typeof NonAuthedLoginSsoCallbackRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/login': typeof NonAuthedLoginIndexRoute
  '/register': typeof NonAuthedRegisterIndexRoute
}

export interface FileRoutesByTo {
  '': typeof NonAuthedRouteRouteWithChildren
  '/': typeof HomeIndexRoute
  '/profile/$username': typeof AuthedProfileUsernameRoute
  '/login/sso-callback': typeof NonAuthedLoginSsoCallbackRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/login': typeof NonAuthedLoginIndexRoute
  '/register': typeof NonAuthedRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_nonAuthed': typeof NonAuthedRouteRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/_authed/profile/$username': typeof AuthedProfileUsernameRoute
  '/_nonAuthed/login/sso-callback': typeof NonAuthedLoginSsoCallbackRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_nonAuthed/login/': typeof NonAuthedLoginIndexRoute
  '/_nonAuthed/register/': typeof NonAuthedRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/profile/$username'
    | '/login/sso-callback'
    | '/profile'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/profile/$username'
    | '/login/sso-callback'
    | '/profile'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/_authed'
    | '/_nonAuthed'
    | '/_home/'
    | '/_authed/profile/$username'
    | '/_nonAuthed/login/sso-callback'
    | '/_authed/profile/'
    | '/_nonAuthed/login/'
    | '/_nonAuthed/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  NonAuthedRouteRoute: typeof NonAuthedRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  NonAuthedRouteRoute: NonAuthedRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/_nonAuthed",
        "/_home/"
      ]
    },
    "/_authed": {
      "filePath": "_authed/route.tsx",
      "children": [
        "/_authed/profile/$username",
        "/_authed/profile/"
      ]
    },
    "/_nonAuthed": {
      "filePath": "_nonAuthed/route.tsx",
      "children": [
        "/_nonAuthed/login/sso-callback",
        "/_nonAuthed/login/",
        "/_nonAuthed/register/"
      ]
    },
    "/_home/": {
      "filePath": "_home/index.tsx"
    },
    "/_authed/profile/$username": {
      "filePath": "_authed/profile/$username.tsx",
      "parent": "/_authed"
    },
    "/_nonAuthed/login/sso-callback": {
      "filePath": "_nonAuthed/login/sso-callback.tsx",
      "parent": "/_nonAuthed"
    },
    "/_authed/profile/": {
      "filePath": "_authed/profile/index.tsx",
      "parent": "/_authed"
    },
    "/_nonAuthed/login/": {
      "filePath": "_nonAuthed/login/index.tsx",
      "parent": "/_nonAuthed"
    },
    "/_nonAuthed/register/": {
      "filePath": "_nonAuthed/register/index.tsx",
      "parent": "/_nonAuthed"
    }
  }
}
ROUTE_MANIFEST_END */
